# Generated by Django 4.2.7 on 2023-11-28 15:31

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BecomeAMemberFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='file/%d/%m')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.becomeamember')),
            ],
        ),
    ]
